config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root to: 'homes#top'
  patch 'customers/:id/image' => 'customers#update_image',  as: 'customer_image'
  # patch 'customers/sitter/:id' => 'customers#update_sitter', as: 'update_sitter_customer_patch'
  post 'customers/sitter/:id/edit' => 'customers#edit_sitter', as: 'edit_sitter_customer_post'
  post 'customers/sitter/:id' => 'customers#sitter_show', as: 'sitter_customer_post'
  # get 'customers/sitter/:id' => 'customers#sitter_show', as: 'sitter_customer'
  # get 'customers/sitter/:id/edit' => 'customers#sitter_edit', as: 'edit_sitter_customer'
  resources :my_reservations, only: [:index, :update]
  resources :customers, only: [:new, :show, :index, :edit, :update] do
    resources :sitters do
       resources :favorites, only: [:create, :destroy, :index]
       resources :reservations
       resources :reviews, only: [:new, :create, :destroy]
    end
  end
  get 'reservations' => 'reservations#list', as: 'reservation_lists'
  resources :pets, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :customer_rooms, only: [:show, :create]
  post 'customers_room/:id' => 'customer_room#show', as: 'customer_room_show'
  resources :chats, only: [:create, :show]
  # get 'reservations/:id' => 'reservations#index', as: 'reservations_the'
  # For details on the DSL within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many_attached :images

  has_many :customer_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :reservations, dependent: :destroy
  # has_many :favorites, dependent: :destroy
  # has_many :sitters, through: :favorites, source: :sitter

  has_many :favorites, class_name: "Favorite", foreign_key: :sitter_id
  has_many :sitters, through: :favorites, source: :sitter

  def favorite?(customer) #customerはcurrent_customer
    favorites.where(customer_id: customer.id, sitter_id: self.id).exists? #selfは@sitter
  end

end

app/models/customer_room.rb
class CustomerRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :sitter, class_name: 'Customer'
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many_attached :images
  # has_many :sitter_pets, dependent: :destory
end

app/models/reception.rb
class Reception < ApplicationRecord
  # belongs_to :customer
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :customer
  has_many :reviews, dependent: :destroy

  validates :day, presence: true
  validates :time, presence: true
  validates :start_time, presence: true, uniqueness: true

  validate :date_before_start
  validate :date_current_today
  validate :date_three_month_end

  def date_before_start
    return if day < Date.current
    errors.add(:day, "は過去の日付は選択できません。予約画面から正しい日付を選択してください。")
  end

  def date_current_today
    errors.add(:day, "は当日は選択できません。予約画面から正しい日付を選択してください。") if day < (Date.current + 1)
  end

  def date_three_month_end
    errors.add(:day, "は3ヶ月以降の日付は選択できません。予約画面から正しい日付を選択してください。") if (Date.current >> 3) < day
  end

  def self.check_reservation_day(day)
    if day < Date.current
      return "過去の日付は選択できません。正しい日付を選択してください。"
    elsif day < (Date.current + 1)
      return "当日は選択できません。正しい日付を選択してください。"
    elsif (Date.current >> 3) < day
      return "3ヶ月以降の日付は選択できません。正しい日付を選択してください。"
    end
  end

  def self.reservations_after_three_month
    reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :customer_rooms
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create params.require(:pet).permit(:customer_id, :name, :age, :sex, :color, :kind, :introduction, images: [])
    redirect_to @pet
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update params.require(:pet).permit(:customer_id, :name, :age, :sex, :color, :kind, :introduction, images: [])
    redirect_to @pet
  end

  def destroy
    pet = Pet.find(params[:id])
    pet.images.purge #active storageの画像のみ削除
    flash[:notice] = "削除しました"
    redirect_to action: "index"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/fovarites_helper.rb
module FovaritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/petses_helper.rb
module PetsesHelper
end

app/helpers/receptions_helper.rb
module ReceptionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/views/pets/edit.html.erb
<h1>ペット画像編集</h1>

<% if @pet.images.attached? %>
  <% @pet.images.each do |image| %>
    <%= image_tag image, size: 10*10 %> <br>
  <% end %>
<% end %>
<%= link_to "削除", pet_path(@pet.id), method: :delete, data: { confirm: '削除してもよろしいですか？' } %>

<%= form_with model: @pet, local: true do |f| %>
  ペットの画像  <%= f.file_field :images, multiple: true %></br>
  ペットの名前  <%= f.text_field :name %></br>
  ペットの年齢  <%= f.text_field :age %></br>
  ペットの性別  <%= f.text_field :sex %></br>
  ペットの毛色  <%= f.text_field :color %></br>
  ペットの種類  <%= f.text_field :kind %></br>
  ペットの説明  <%= f.text_field :introduction %></br>
  <%= f.submit "保存する" %>
<% end %>

app/views/pets/index.html.erb
<h1>あなたのペット</h1>

<%= link_to "ペット画像登録", new_pet_path %></br>


<% @pets.each do |pet| %>

  <%=link_to pet_path(pet.id) do %>

    <% if pet.images.attached? %>
      <% pet.images.each do |image| %>
        <%= image_tag image, size: 10*10 %><br>
        クリックで詳細画面へ
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/pets/new.html.erb
<h1>ペット登録</h1>

<%= form_with model: @pet, local: true do |f| %>
  ペットの画像  <%= f.file_field :images, multiple: true %></br>
  ペットの名前  <%= f.text_field :name %></br>
  ペットの年齢  <%= f.text_field :age %></br>
  ペットの性別  <%= f.text_field :sex %></br>
  ペットの毛色  <%= f.text_field :color %></br>
  ペットの種類  <%= f.text_field :kind %></br>
  ペットの説明  <%= f.text_field :introduction %></br>
  <%= f.submit "登録する" %>
<% end %>

app/views/pets/show.html.erb
<h1>ペット詳細</h1>

<% if @pet.images.attached? %>
  <% @pet.images.each do |image| %>
    <%= image_tag image, size: 10*10 %><br>
  <% end %>
<% end %>
<%= @pet.name %>
<%= @pet.age %>
<%= @pet.sex %>
<%= @pet.color %>
<%= @pet.kind %>
<%= @pet.introduction %>

<%= link_to "編集", edit_pet_path(@pet.id) %>